version: '3.7'

services:

  api:
    container_name: pricing-chris-api
    build: '.'
    environment:
      PG_HOST: pricing-db
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3333:3333'
    depends_on:
      - db

  db:
    container_name: pricing-db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD} 
    ports: 
      - '5432:5432'
    volumes:
      - pricing-db-data:/var/lib/postgresql/data

volumes:
  pricing-db-data: